// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperacaoCuriosidade.Persistence;

#nullable disable

namespace OperacaoCuriosidade.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OperacaoCuriosidade.Entities.Cadastro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Atividade")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
<<<<<<< Updated upstream
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Endereço");
=======
                        .HasColumnType("nvarchar(250)");
>>>>>>> Stashed changes

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Interesses")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OutrasInformacoes")
                        .HasMaxLength(250)
<<<<<<< Updated upstream
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Outras Informações");
=======
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");
>>>>>>> Stashed changes

                    b.Property<string>("Sentimentos")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Valores")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

<<<<<<< Updated upstream
                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

=======
>>>>>>> Stashed changes
                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("OperacaoCuriosidade.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

<<<<<<< Updated upstream
=======
                    b.Property<string>("Secret")
                        .HasColumnType("nvarchar(max)");

>>>>>>> Stashed changes
                    b.Property<string>("Senha")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
